[package]
name = "simple_service"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.12.0"
actix-web = "3.3.2"
async-std = "1.9.0"
serde = "1.0.126"
sqlx = { version = "0.4.1", runtime = "actix", features = ["runtime-tokio-rustls", "postgres"]}
tokio = "1.8.1"
